version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db-container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pomodoro-db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - rede-pomodoro

  frontend:
    build: .
    container_name: frontend
    env_file:
      - .env
    expose:
      - "80"
    networks:
      - rede-pomodoro
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - rede-pomodoro

networks:
  rede-pomodoro:
    driver: bridge

volumes:
  pomodoro-db-data:
